### ISSUE TITLE
[Bug] Punctuations and other characters

### ISSUE THREAD

**Issue by svejdani** [amirhhashemi/tiptap-text-direction#11]
Hello, 

I was wondering if it's possible to properly align punctuations when writing English in RTL text. 

Example: 
![image](https://user-images.githubusercontent.com/105304186/235475814-79e2aed0-ec62-490f-848c-dfab3e27b17f.png)

As you can see the question mark is on the wrong side and it behaves the same in the TipTap editor. 

Let me know, 
Thanks

**Comment by amirhhashemi** [comment]
As far as I know, it's a problem with the Unicode Bidirectional Algorithm. Sometimes when we have a text with different directions the algorithm needs help to show the text (and especially punctuation) correctly. There are various ways that we can help the algorithm, but I can't think of an easy way to implement them in a plugin. Please read [Inline markup and bidirectional text in HTML](https://www.w3.org/International/articles/inline-bidi-markup) if you need more information.

Github and [Lexical](https://playground.lexical.dev/) has the same problem. I'm not smarter than those guys so maybe there is not a solution for this yet.
