### ISSUE TITLE
How to detect current direction ?

### ISSUE THREAD

**Issue by ramyahm2010** [amirhhashemi/tiptap-text-direction#14]
Hello,

Kindly, need a way to detect active current direction (rtl / ltr), i tried following:

`editor.isActive({ textDirection: "rtl" });`

but always returns `false` even if it's already current active direction !

**Comment by amirhhashemi** [comment]
Hi,
Try this:
```jsx
editor.isActive({ dir: "rtl" });
```
Because the global attribute's name is `dir` not `textDirection`. But I think `textDirection` makes more sense. I will update it in a future release.

**Comment by ramyahm2010** [comment]
Thanks @amirhhashemi 

Tried provided code & it's working fine.
