### ISSUE TITLE
[Bug] Pasting multi-line text

### ISSUE THREAD

**Issue by amirhhashemi** [amirhhashemi/tiptap-text-direction#8]
When a multi-line text is pasted to the editor, it only calculates the direction for the first line (node). 

Originally reported by @coderyeasin in https://github.com/ueberdosis/tiptap/issues/3085#issuecomment-1505848844

**Comment by coderyeasin** [comment]
Thank you so much for your response!
when you're done please ensure me a message.

Best of luck!

**Comment by amirhhashemi** [comment]
It should be fixed in the latest version (`0.2.3`).

I'm gonna close this but feel free to re-open it if you still encounter the issue.
